apiVersion: v1
kind: Service
metadata:
  name: inventory-api-service
  labels:
    app: inventory-api
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 80
  selector:
    app: inventory-api