apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: get-list-services-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: api-service-account
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: get-list-services-cluster-role
  apiGroup: rbac.authorization.k8s.io