apiVersion: v1
kind: Service
metadata:
  name: inventory-api-lb
  labels:
    app: inventory-api
spec:
  type: LoadBalancer
  ports:
    - port: 8090
      targetPort: 80
  selector:
    app: inventory-api